<?php

// Autoloading (automatically generated by composer)
require '../vendor/autoload.php';

//Initialize Application
$app = require 'init/init.php';
$router = require 'router.php';
$router($app);

// Launch application
$app->run();